name: dukou check-in script

on:
  push:
    branches:
      - main
  schedule:
    - cron: "30 12 * * *"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: 'download chromedriver'
      run: wget https://chromedriver.storage.googleapis.com/113.0.5672.63/chromedriver_linux64.zip
    - name: 'unzip chromedriver'
      run: unzip chromedriver_linux64.zip
    - name: 'add to path'
      run:
        echo 'export PATH=$PATH:./chromedriver_linux64/chromedriver' >> ~/.bash_profile
        source ~/.bash_profile
    - name: 'Install requirements'
      run: pip3 install selenium
    - name: Run dukou check-in script
      env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWD: ${{ secrets.PASSWD }}
      run:
        python3 checkin.py
